version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Jaye-prod
    ports:
      - "8000:80"
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env